#!/bin/bash

echo ">>>>> REMOVING NODE MODULES AND PACKAGE LOCK - $1"
rm -rf "../$1/node_modules" "../$1/package-lock.json"
echo ">>>>> FIXING MANUAL LINKS - $1"
node --experimental-modules "src/$1.mjs"
cd "../$1"
echo ">>>>> INSTALLING DEPENDENCIES ANEW - $1"
npm i